### PR TITLE
Adding support for host-shared folders using virtio-9p

### PR DESCRIPTION
**Pull request by stv0g**
**Please consider this PR a WiP.**

@jceel has implemented support for host-shared directories / mounts like requested in #45 and #70.

There are a few points we still need to tackle.
And the best way to do this is by getting some feedback. Especially from @mist64 :-)
- [ ] Are you fine with introducing new dependencies like jceel's lib9p?
- [ ] How do you want to track dependencies:
  - git submodule?
  - pkg-config
  - ??
- [ ] Allow building without virtio-9p support
- [ ] [lib9p](https://github.com/jceel/lib9p) is not based on on [Plan 9 lib9p](http://man.cat-v.org/plan_9/2/9p) nor [libixp](http://libs.suckless.org/libixp). We should clarify that in the README of jceel's lib9p.

### CODE REVIEW

**Comment by c4milo** [comment]
I'm all for getting libp9 introduced into xhyve. Any thoughts on this @xez?

**Comment by stv0g** [comment]
@c4milo What do you mean by 'introduced'?

Using a git-submodule? Or by copy&paste the code?
Or even without all?

**Comment by c4milo** [comment]
Whatever method is more convenient to update from upstream.

**Comment by foxx** [comment]
Any update on this?

**Comment by stv0g** [comment]
I lost the overview which repo is now the _official_ one.
I don't know where its merged or not.

**Comment by smiren** [comment]
What news?

**Comment by mfojtik** [comment]
Seems like this needs a rebase as this won't build on latest OSX :-(

**Comment by dinamic** [comment]
Guys, it will be awesome if we could have this functionality baked in. Is there any progress?

**Comment by jeremyhu** [comment]
@jasnee Was looking at this a couple weeks ago for me.  There were some comments he wanted to pass along before we merge this in.  James, could you please provide your feedback here?

**Comment by stv0g** [comment]
Sorry. I dont have any interest anymore in getting this merged.

If there is anybody else, please feel free to open a new PR with my changes rebased..

**Pull request closed without merging**
