### PR TITLE
Migrate vmm_callout -> OSX libdispatch

### PR DESCRIPTION
**Pull request by bonifaido**
Tries to be a cleaner implementation then the current one, based upon what I saw in README.md - TODO I thought it was a good idea to migrate it. I wouldn't say it is complete, but it could be a good starting point. I haven't seen any issues by running a VM for a couple of hours with multiple sleeps with this patch.

### CODE REVIEW

**Comment by jeremyhu** [comment]
Have you done any performance comparisons before and after your changes?

**Comment by bonifaido** [comment]
Just rebased on master.

**Comment by bonifaido** [comment]
Tried the Tiny Linux boot, and it still works with the rebased version.

I have run performance tests in the past (2 years ago) and they looked better than the original implementation (and if I just could remember how did I they looked like!). What would you suggest, how to exercise it? I think it would make sense to test it again.

**Comment by bonifaido** [comment]
@machyve/write-access do you think this still something that is worth to merge? I can try to spend some time on it to get it tested again.

**Comment by yurikoles** [comment]
@bonifaido it seems like project is semi-dead.

**Comment by catap** [comment]
@jeremyhu can you take a look on this?

**Review by jeremyhu — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
